// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: esphome_api_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from esphome_api_options.proto</summary>
public static partial class EsphomeApiOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for esphome_api_options.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EsphomeApiOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chllc3Bob21lX2FwaV9vcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYv",
          "ZGVzY3JpcHRvci5wcm90byIJCgd2b2lkbXNnKkYKDUFQSVNvdXJjZVR5cGUS",
          "DwoLU09VUkNFX0JPVEgQABIRCg1TT1VSQ0VfU0VSVkVSEAESEQoNU09VUkNF",
          "X0NMSUVOVBACOkUKFm5lZWRzX3NldHVwX2Nvbm5lY3Rpb24SHi5nb29nbGUu",
          "cHJvdG9idWYuTWV0aG9kT3B0aW9ucxiOCCABKAg6BHRydWU6QwoUbmVlZHNf",
          "YXV0aGVudGljYXRpb24SHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9u",
          "cxiPCCABKAg6BHRydWU6LwoCaWQSHy5nb29nbGUucHJvdG9idWYuTWVzc2Fn",
          "ZU9wdGlvbnMYjAggASgNOgEwOk0KBnNvdXJjZRIfLmdvb2dsZS5wcm90b2J1",
          "Zi5NZXNzYWdlT3B0aW9ucxiNCCABKA4yDi5BUElTb3VyY2VUeXBlOgtTT1VS",
          "Q0VfQk9USDovCgVpZmRlZhIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0",
          "aW9ucxiOCCABKAk6MwoDbG9nEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VP",
          "cHRpb25zGI8IIAEoCDoEdHJ1ZTo5Cghub19kZWxheRIfLmdvb2dsZS5wcm90",
          "b2J1Zi5NZXNzYWdlT3B0aW9ucxiQCCABKAg6BWZhbHNl"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::APISourceType), }, new pb::Extension[] { EsphomeApiOptionsExtensions.NeedsSetupConnection, EsphomeApiOptionsExtensions.NeedsAuthentication, EsphomeApiOptionsExtensions.Id, EsphomeApiOptionsExtensions.Source, EsphomeApiOptionsExtensions.Ifdef, EsphomeApiOptionsExtensions.Log, EsphomeApiOptionsExtensions.NoDelay }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::voidmsg), global::voidmsg.Parser, null, null, null, null, null)
        }));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of esphome_api_options.proto</summary>
public static partial class EsphomeApiOptionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> NeedsSetupConnection =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(1038, pb::FieldCodec.ForBool(8304, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> NeedsAuthentication =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(1039, pb::FieldCodec.ForBool(8312, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, uint> Id =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, uint>(1036, pb::FieldCodec.ForUInt32(8288, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::APISourceType> Source =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::APISourceType>(1037, pb::FieldCodec.ForEnum(8296, x => (int) x, x => (global::APISourceType) x, global::APISourceType.SourceBoth));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> Ifdef =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(1038, pb::FieldCodec.ForString(8306, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> Log =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(1039, pb::FieldCodec.ForBool(8312, true));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> NoDelay =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(1040, pb::FieldCodec.ForBool(8320, false));
}

#region Enums
public enum APISourceType {
  [pbr::OriginalName("SOURCE_BOTH")] SourceBoth = 0,
  [pbr::OriginalName("SOURCE_SERVER")] SourceServer = 1,
  [pbr::OriginalName("SOURCE_CLIENT")] SourceClient = 2,
}

#endregion

#region Messages
public sealed partial class voidmsg : pb::IMessage<voidmsg>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<voidmsg> _parser = new pb::MessageParser<voidmsg>(() => new voidmsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<voidmsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EsphomeApiOptionsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public voidmsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public voidmsg(voidmsg other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public voidmsg Clone() {
    return new voidmsg(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as voidmsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(voidmsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(voidmsg other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
